const test=require('node:test'),assert=require('node:assert/strict'),loader=require('./ts-loader.cjs');
const token='private-bot-test-only-credential-'.repeat(2),worker='worker-test-only-credential-'.repeat(2);
const env={TELEGRAM_BACKEND_TOKEN:token,TELEGRAM_ADMIN_USER_IDS:'123,456',AUTOMATION_WORKER_CREDENTIALS:JSON.stringify({worker})};
function req(body={},secret=token,actor='123'){return new Request('https://hdqaz.online/api/telegram/admin',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+secret,'X-Telegram-User-Id':actor},body:JSON.stringify(body)});}
test('bot auth default deny numeric whitelist and separate worker/admin credentials',()=>{const load=loader({},env),{botAuth}=load('src/features/telegram/auth.ts');assert.equal(botAuth(req()),123);for(const actor of ['','name','0','999','0123'])assert.throws(()=>botAuth(req({},token,actor)));for(const s of [worker,'wrong',''])assert.throws(()=>botAuth(req({},s)));const other=loader({},{...env,TELEGRAM_BACKEND_TOKEN:worker});assert.throws(()=>other('src/features/telegram/auth.ts').botAuth(req({},worker)));});
test('TMDB mapping validates identity, paths, dates and fallbacks',()=>{const {tmdbMap}=loader({},env)('src/features/telegram/tmdb.ts');const m=tmdbMap({id:5,title:' Test ',release_date:'2026-01-01',poster_path:'/abc.jpg',backdrop_path:'https://evil.test/a',runtime:120,genres:[{name:'Drama'}],production_countries:[{iso_3166_1:'KZ'}]},'movie');assert.equal(m.title,'Test');assert.equal(m.year,2026);assert.equal(m.country,'KZ');assert.equal(m.banner_url,'');assert.equal(m.poster_url,'https://image.tmdb.org/t/p/w780/abc.jpg');assert.throws(()=>tmdbMap({id:-1,title:'x'},'movie'));assert.equal(tmdbMap({id:2,name:'Series',first_air_date:'2025-02-02'},'series').year,2025);});
test('metadata rejects external credentials URLs, unknown fields and publication flags',()=>{const {metadata}=loader({},env)('src/features/telegram/validation.ts');for(const x of [{is_published:true},{hls_url:'https://evil/a.m3u8'},{year:0},{season_number:-1},{poster_url:'https://user:secret@image.tmdb.org/a'},{source_url:'https://private'}])assert.throws(()=>metadata(x));assert.deepEqual(JSON.parse(JSON.stringify(metadata({title:'Kazakh',year:2026,is_premium:false}))),{title:'Kazakh',year:2026,is_premium:false});});
test('private API rejects unauthorized input before database and sanitizes internal errors',async()=>{let touched=0;const load=loader({'@/lib/supabase/admin':{createAdminClient(){touched++;throw Error('secret token stack internal');}}},env);const {telegramRequest}=load('src/features/telegram/http.ts');assert.equal((await telegramRequest(req({action:'queue'},'wrong'))).status,401);assert.equal(touched,0);const result=await telegramRequest(req({action:'queue'}));assert.equal(result.status,503);assert.doesNotMatch(await result.text(),/secret|token|stack/);});
test('oversized request is rejected and no raw payload is echoed',async()=>{const {jsonBody}=loader({},env)('src/features/telegram/validation.ts');await assert.rejects(jsonBody(req({action:'edit',data:'x'.repeat(17000)})));});

test('TMDB search and detail fallback use fixtures, never production',async()=>{const calls=[];const fetch=async(url)=>{calls.push(url);const data=url.includes('/search/')?{results:[{id:1,title:'Result',release_date:'2020-01-01'}]}:{id:1,title:'Result',overview:url.includes('en-US')?'Fallback text':'',release_date:'2020-01-01'};return new Response(JSON.stringify(data));};const mod=loader({}, {...env,TMDB_ACCESS_TOKEN:'test-only'}, {fetch,AbortSignal})('src/features/telegram/tmdb.ts');assert.equal((await mod.tmdbSearch('movie','Result'))[0].title,'Result');assert.equal((await mod.tmdbDetails('movie',1)).description,'Fallback text');assert.equal(calls.length,3);assert.ok(calls.every(x=>x.startsWith('https://api.themoviedb.org/3/')));});
test('catalog patch only changes allowed metadata and classification stays independent',()=>{const {catalogPatch,classification}=loader({},env)('src/features/telegram/catalog.ts');for(const d of [null,[],{}, {slug:'new'}, {hls_url:'https://x'}, {is_published:true},{type:'movie'},{section:'anime'}])assert.throws(()=>catalogPatch(d));assert.equal(catalogPatch({dubber_id:null}).dubber_id,null);assert.equal(catalogPatch({title:'New'}).title,'New');assert.equal(classification({type:'movie',section:'anime'}).kind,'movie');assert.equal(classification({type:'series',section:'dorama'}).section,'dorama');});
test('catalog actions require actor authorization before reading the database',async()=>{let touched=0;const mod=loader({'@/lib/supabase/admin':{createAdminClient(){touched++;return {};}}},env)('src/features/telegram/http.ts');const res=await mod.telegramRequest(req({action:'catalog'},token,'999'));assert.equal(res.status,403);});
test('existing movie attach accepts only empty unpublished movie targets',async()=>{
 const id='11111111-1111-4111-8111-111111111111';
 for(const record of [{type:'movie',hls_url:null,is_published:false},{type:'movie',hls_url:null,is_published:true},{type:'movie',hls_url:'https://cdn.hdqaz.online/old.m3u8',is_published:false},{type:'series',hls_url:null,is_published:false}]){
  let mutation;const c={id,title:'Web draft',year:2026,section:'default',description:'',country:'',duration_minutes:null,dubber_id:null,is_premium:false,...record};const w={id,kind:'movie',metadata:{},revision:0};
  const db={from(table){const q={};for(const k of ['select','eq','single','maybeSingle'])q[k]=()=>q;q.then=resolve=>resolve({data:table==='contents'?c:w,error:null});return q;},rpc:async(name,data)=>{mutation=data;return {data:w,error:null};}};
  const mod=loader({'@/lib/supabase/admin':{createAdminClient:()=>db}},env)('src/features/telegram/http.ts');const response=await mod.telegramRequest(req({action:'existing',id,revision:0,request_id:id,data:{content_id:id}}));
  const valid=!record.is_published&&!record.hls_url&&record.type==='movie';assert.equal(response.status,valid?200:400);if(valid)assert.equal(mutation.p_data.existing_content_id,id);else assert.equal(mutation,undefined);
 }
});
