const test=require('node:test'),assert=require('node:assert/strict'),sharp=require('sharp'),loader=require('./ts-loader.cjs');
const id='11111111-1111-4111-8111-111111111111',key='22222222-2222-4222-8222-222222222222',token='test-private-backend-token-'.repeat(2),env={TELEGRAM_BACKEND_TOKEN:token,TELEGRAM_ADMIN_USER_IDS:'123',NEXT_PUBLIC_SUPABASE_URL:'https://test.supabase.co'};
const image=fmt=>sharp({create:{width:16,height:12,channels:3,background:'blue'}}).toFormat(fmt).toBuffer();
const req=(data,extra={})=>new Request('https://hdqaz.online/api/telegram/media',{method:'POST',headers:{Authorization:'Bearer '+token,'X-Telegram-User-Id':'123','Content-Type':'image/webp','X-Target-Id':id,'X-Media-Field':'poster_url','X-Workflow':'false','X-Version':'2026-10-05T00:00:00Z','X-Request-Id':key,...extra},body:data});
function fixture(flow=false,overrides={}){let saved,rpc=[],uploads=0;const target=flow?{id,actor_id:123,state:'draft',revision:0,metadata:{title:'Draft',year:2026}}:{id,updated_at:'2026-10-05T00:00:00Z',poster_url:'old',banner_url:'old-banner'};Object.assign(target,overrides);
 const store={getPublicUrl:path=>({data:{publicUrl:'https://test.supabase.co/storage/v1/object/public/content-media/'+path}}),upload:async(path,data)=>{uploads++;saved=data;return {error:null}},download:async()=>({data:saved?new Blob([saved]):null,error:saved?null:{}})};
 const db={from(){const q={};for(const name of ['select','eq','single'])q[name]=()=>q;q.then=resolve=>resolve({data:target,error:null});return q;},storage:{from:()=>store},rpc:async(name,data)=>{rpc.push({name,data});return {data:{},error:null}}};
 const mod=loader({'sharp':{default:sharp},'@/lib/supabase/admin':{createAdminClient:()=>db}},env)('src/features/telegram/media.ts');return {mod,rpc,store,uploads:()=>uploads};}
test('common inputs normalize to bounded WEBP; non-images rejected',async()=>{const {normalizeImage}=fixture().mod;for(const fmt of ['jpeg','png','webp'])assert.equal((await sharp(await normalizeImage(await image(fmt))).metadata()).format,'webp');await assert.rejects(normalizeImage(Buffer.from('secret-not-an-image')));await assert.rejects(normalizeImage(await image('gif')));});
test('auth and actor whitelist rejected before storage writes',async()=>{const f=fixture(),data=await image('webp');assert.equal((await f.mod.mediaRequest(req(data,{Authorization:'Bearer wrong'}))).status,401);assert.equal((await f.mod.mediaRequest(req(data,{'X-Telegram-User-Id':'999'}))).status,403);assert.equal(f.uploads(),0);});
test('catalog replacement only patches existing image field with version check',async()=>{const f=fixture();const response=await f.mod.mediaRequest(req(await image('png'),{'Content-Type':'image/png'}));assert.equal(response.status,200);const result=(await response.json()).data;assert.match(result.url,/content-media\/posters\/11111111.*poster-/);assert.equal(f.rpc[0].name,'telegram_catalog_action');assert.deepEqual(JSON.parse(JSON.stringify(f.rpc[0].data.p_data)),{poster_url:result.url});assert.equal(f.rpc[0].data.p_expected,'2026-10-05T00:00:00Z');});
test('draft upload changes only workflow metadata, never creates content/source/job',async()=>{const f=fixture(true);const response=await f.mod.mediaRequest(req(await image('webp'),{'X-Workflow':'true','X-Version':'0','X-Media-Field':'banner_url'}));assert.equal(response.status,200);assert.equal(f.rpc[0].name,'telegram_workflow_action');assert.equal(f.rpc[0].data.p_action,'edit');assert.equal(f.rpc[0].data.p_data.title,'Draft');assert.match(f.rpc[0].data.p_data.banner_url,/banners\/drafts\//);});
test('stale/terminal workflow and malformed targets cannot upload',async()=>{for(const headers of [{'X-Version':'2026-10-04T00:00:00Z'},{'X-Target-Id':'../../evil'},{'X-Media-Field':'hls_url'}]){const f=fixture();assert.ok((await f.mod.mediaRequest(req(await image('webp'),headers))).status>=400);assert.equal(f.uploads(),0);}const f=fixture(true,{state:'submitted'});assert.equal((await f.mod.mediaRequest(req(await image('webp'),{'X-Workflow':'true','X-Version':'0'}))).status,409);assert.equal(f.uploads(),0);});
test('storage failure or oversized body does not update database',async()=>{const f=fixture();f.store.upload=async()=>({error:{}});assert.equal((await f.mod.mediaRequest(req(await image('webp')))).status,503);assert.equal(f.rpc.length,0);const g=fixture();assert.equal((await g.mod.mediaRequest(req(Buffer.alloc(3*1024*1024+1)))).status,413);assert.equal(g.rpc.length,0);});
test('only this project media bucket URLs are accepted as workflow metadata',()=>{const {metadata}=loader({},env)('src/features/telegram/validation.ts');assert.ok(metadata({poster_url:'https://test.supabase.co/storage/v1/object/public/content-media/posters/'+id+'/poster.webp'}));for(const url of ['https://other.supabase.co/storage/v1/object/public/content-media/posters/a.webp','https://test.supabase.co/storage/v1/object/public/other/a.webp'])assert.throws(()=>metadata({poster_url:url}));});

test('existing site image template renders own Supabase bucket instead of fallback',()=>{const {getMovieImageSrc}=loader({},env)('src/lib/movie-images.ts');const url='https://test.supabase.co/storage/v1/object/public/content-media/posters/'+id+'/poster.webp';assert.equal(getMovieImageSrc(url,'poster'),url);assert.equal(getMovieImageSrc(url.replace('test.supabase.co','other.supabase.co'),'poster'),'/movie-poster-fallback.svg');});
